/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject1.gui;
import com.mycompany.mavenproject1.RpgCharacter;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Image; 
import java.io.File;   
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
/**
 *
 * @author sever
 */
public class FrCreateCharacter extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrCreateCharacter.class.getName());

 
       private ArrayList<RpgCharacter> characters = new ArrayList<>();
    private String caminhoImagem;
    
    /**
     * Creates new form CreateCharacter
     */
    public FrCreateCharacter() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfCharacterName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbRpgClass = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfStrength = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfAgility = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfIntelligence = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        tfVitality = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        LbnImagem = new javax.swing.JLabel();
        BtnSalvarImagem = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelNameChar1 = new javax.swing.JLabel();
        labelNameChar2 = new javax.swing.JLabel();
        labelNameChar3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnBattleRun = new javax.swing.JButton();
        btnCommonAttack = new javax.swing.JButton();
        btnClassAttack = new javax.swing.JButton();
        btnDeflect = new javax.swing.JButton();
        labelChar1Name = new javax.swing.JLabel();
        labelChar2Name = new javax.swing.JLabel();
        labelChar3Name = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        labelChar1HP = new javax.swing.JLabel();
        labelChar2HP = new javax.swing.JLabel();
        labelChar3HP = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        labelEnemy1HP = new javax.swing.JLabel();
        labelEnemy2HP = new javax.swing.JLabel();
        labelEnemy3HP = new javax.swing.JLabel();
        labelEnemy1Name = new javax.swing.JLabel();
        labelEnemy2Name = new javax.swing.JLabel();
        labelEnemy3Name = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCharacterEditorCard = new javax.swing.JMenuItem();
        miTeamEditorCard = new javax.swing.JMenuItem();
        miBattleCard = new javax.swing.JMenuItem();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(630, 630));

        jPanel1.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(242, 242, 242));
        jLabel1.setText("cadastro de personagem");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(242, 242, 242));
        jLabel2.setText("Nome:");

        tfCharacterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCharacterNameActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(242, 242, 242));
        jLabel3.setText("Classe:");

        cbRpgClass.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Guerreiro", "Arqueiro", "Mago" }));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(242, 242, 242));
        jLabel4.setText("Atributos");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(242, 242, 242));
        jLabel5.setText("Você tem 15 pontos para gastar");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(242, 242, 242));
        jLabel6.setText("Força:");

        tfStrength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfStrengthActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(242, 242, 242));
        jLabel7.setText("Agilidade");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(242, 242, 242));
        jLabel8.setText("Vitalidade");

        btnSalvar.setText("Salvar");
        btnSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvarMouseClicked(evt);
            }
        });
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(242, 242, 242));
        jLabel13.setText("Inteligência");

        LbnImagem.setForeground(new java.awt.Color(242, 242, 242));
        LbnImagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LbnImagem.setText("Imagem");
        LbnImagem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(242, 242, 242)));

        BtnSalvarImagem.setText("Salvar Imagem");
        BtnSalvarImagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnSalvarImagemMouseClicked(evt);
            }
        });
        BtnSalvarImagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarImagemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfIntelligence, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(tfAgility, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                                    .addComponent(tfVitality)
                                    .addComponent(tfStrength)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(tfCharacterName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbRpgClass, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(173, 173, 173)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(BtnSalvarImagem)
                                .addGap(97, 97, 97))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(LbnImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(169, 169, 169))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(214, 214, 214))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfCharacterName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbRpgClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfStrength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfAgility, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfVitality, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfIntelligence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(40, 40, 40))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(LbnImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(BtnSalvarImagem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnSalvar)
                .addGap(89, 89, 89))
        );

        jPanel1.add(jPanel2, "CharacterEditorCard");

        jLabel12.setText("vizualização do time");

        labelNameChar1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNameChar1.setText("nome1");
        labelNameChar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNameChar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNameChar2.setText("nome2");
        labelNameChar2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNameChar3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelNameChar3.setText("nome3");
        labelNameChar3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Classe", "HP", "Mana", "Força", "Agilidade", "Vitalidade", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Classe", "HP", "Mana", "Força", "Agilidade", "Vitalidade", "null"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
            jTable2.getColumnModel().getColumn(4).setResizable(false);
            jTable2.getColumnModel().getColumn(5).setResizable(false);
            jTable2.getColumnModel().getColumn(6).setResizable(false);
        }

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Batalhar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jLabel11)
                        .addGap(94, 94, 94)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelNameChar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNameChar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelNameChar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel12)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(177, 177, 177)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jScrollPane2)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNameChar2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNameChar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNameChar3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(13, 13, 13)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel3, "TeamEditorCard");

        btnBattleRun.setText("Abandonar Partida");

        btnCommonAttack.setText("Corpo a Corpo");
        btnCommonAttack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCommonAttackMouseClicked(evt);
            }
        });
        btnCommonAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommonAttackActionPerformed(evt);
            }
        });

        btnClassAttack.setText("ataque especial");
        btnClassAttack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClassAttackMouseClicked(evt);
            }
        });

        btnDeflect.setText("Desviar");
        btnDeflect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeflectMouseClicked(evt);
            }
        });

        labelChar1Name.setText("nome1");

        labelChar2Name.setText("nome2");

        labelChar3Name.setText("nome3");

        jLabel19.setText("<iconeClasse>");

        jLabel20.setText("<iconeClasse>");

        jLabel21.setText("<iconeClasse>");

        labelChar1HP.setText("HP");

        labelChar2HP.setText("HP");

        labelChar3HP.setText("HP");

        jLabel25.setText("<iconeClasse>");

        labelEnemy1HP.setText("HP");

        labelEnemy2HP.setText("HP");

        labelEnemy3HP.setText("HP");

        labelEnemy1Name.setText("nome1");

        labelEnemy2Name.setText("nome2");

        labelEnemy3Name.setText("nome3");

        jLabel32.setText("<iconeClasse>");

        jLabel33.setText("<iconeClasse>");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelChar1Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelChar2Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelChar3Name)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel21)))
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelChar3HP)
                    .addComponent(labelChar2HP)
                    .addComponent(labelChar1HP))
                .addGap(103, 103, 103))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(labelEnemy1Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel32))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(labelEnemy2Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel33))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(labelEnemy3Name)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel25)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEnemy3HP)
                            .addComponent(labelEnemy2HP)
                            .addComponent(labelEnemy1HP)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCommonAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnClassAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBattleRun, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                            .addComponent(btnDeflect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnemy1Name)
                    .addComponent(jLabel32)
                    .addComponent(labelEnemy1HP))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnemy2Name)
                    .addComponent(jLabel33)
                    .addComponent(labelEnemy2HP))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEnemy3Name)
                    .addComponent(jLabel25)
                    .addComponent(labelEnemy3HP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 149, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChar1Name)
                    .addComponent(jLabel19)
                    .addComponent(labelChar1HP))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChar2Name)
                    .addComponent(jLabel20)
                    .addComponent(labelChar2HP))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelChar3Name)
                    .addComponent(jLabel21)
                    .addComponent(labelChar3HP))
                .addGap(69, 69, 69)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClassAttack, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(btnCommonAttack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeflect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44)
                .addComponent(btnBattleRun)
                .addGap(19, 19, 19))
        );

        jPanel1.add(jPanel4, "BattleCard");

        jMenu1.setText("tab");

        miCharacterEditorCard.setText("Character Editor");
        miCharacterEditorCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCharacterEditorCardActionPerformed(evt);
            }
        });
        jMenu1.add(miCharacterEditorCard);

        miTeamEditorCard.setText("Team Editor");
        miTeamEditorCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miTeamEditorCardActionPerformed(evt);
            }
        });
        jMenu1.add(miTeamEditorCard);

        miBattleCard.setText("Battle");
        miBattleCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBattleCardActionPerformed(evt);
            }
        });
        jMenu1.add(miBattleCard);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCharacterEditorCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCharacterEditorCardActionPerformed
        CardLayout cardlayout = (CardLayout) jPanel1.getLayout();
        cardlayout.show(jPanel1,"CharacterEditorCard");
    }//GEN-LAST:event_miCharacterEditorCardActionPerformed

    private void miTeamEditorCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miTeamEditorCardActionPerformed
        CardLayout cardlayout = (CardLayout) jPanel1.getLayout();
        cardlayout.show(jPanel1,"TeamEditorCard");
    }//GEN-LAST:event_miTeamEditorCardActionPerformed

    private void miBattleCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBattleCardActionPerformed
        CardLayout cardlayout = (CardLayout) jPanel1.getLayout();
        cardlayout.show(jPanel1,"BattleCard");       
    }//GEN-LAST:event_miBattleCardActionPerformed

    private void tfCharacterNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCharacterNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCharacterNameActionPerformed

    private void tfStrengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfStrengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfStrengthActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvarMouseClicked
     try {
            String characterName = tfCharacterName.getText();
            if (characterName.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "O nome do personagem não pode estar vazio.", "Erro de Validação", JOptionPane.ERROR_MESSAGE);
                return;
            }

            int intStrength = Integer.parseInt(tfStrength.getText());
            int intAgility = Integer.parseInt(tfAgility.getText());
            int intVitality = Integer.parseInt(tfVitality.getText());
            int intIntelligence = Integer.parseInt(tfIntelligence.getText());
            int totalPoints = intStrength + intVitality + intAgility + intIntelligence;

            if (totalPoints > 15) {
                JOptionPane.showMessageDialog(this,
                    "Você distribuiu " + totalPoints + " pontos.\nO máximo permitido é 15!",
                    "Limite de Pontos Excedido",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }

            
            int classIndex = cbRpgClass.getSelectedIndex();
            RpgCharacter tempchar = new RpgCharacter(characterName, classIndex, intStrength, intAgility, intVitality, intIntelligence);

            
            if (tempchar != null) {
                // Aqui você usaria o Lblimagem se ele estivesse na UI e inicializado
                // Removido temporariamente para evitar NullPointerException se Lblimagem não foi inicializado
                // tempchar.setImagem(caminhoImagem);
                
                this.characters.add(tempchar); 
                
                JOptionPane.showMessageDialog(this, "Personagem cadastrado com sucesso!");

                DefaultTableModel tablemodel = (DefaultTableModel) jTable1.getModel();
                tablemodel.addRow(new Object[]{
                    tempchar.getName(),
                    tempchar.getRpgClassName(),
                    Integer.toString(tempchar.getStamina()),
                    Integer.toString(tempchar.getMana()),
                    Integer.toString(tempchar.getStrength()),
                    Integer.toString(tempchar.getAgility()),
                });

                limparCampos();
            }
        } catch (NumberFormatException e) {
            // Captura o erro se o usuário digitar texto em vez de números
            JOptionPane.showMessageDialog(this, "Por favor, insira apenas números inteiros nos campos de atributos.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
        }
                                     
    }//GEN-LAST:event_btnSalvarMouseClicked
private void limparCampos(){

tfCharacterName.setText("");

tfStrength.setText("");

tfAgility.setText("");

tfVitality.setText("");

tfIntelligence.setText("");

cbRpgClass.setSelectedIndex(0);

LbnImagem.setIcon(null); 

LbnImagem.setText("Imagem");
caminhoImagem = null;
}
    private void btnCommonAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommonAttackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCommonAttackActionPerformed

    private void btnCommonAttackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCommonAttackMouseClicked
        
        // invoca a função "commonAttack" da classe "Character"
    }//GEN-LAST:event_btnCommonAttackMouseClicked

    private void btnClassAttackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClassAttackMouseClicked
        // invoca a função "specialAttack" da classe "Character"
    }//GEN-LAST:event_btnClassAttackMouseClicked

    private void btnDeflectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeflectMouseClicked
        // invoca a função "deflect" da classe "Character"
    }//GEN-LAST:event_btnDeflectMouseClicked

    private void BtnSalvarImagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarImagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSalvarImagemActionPerformed

    private void BtnSalvarImagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnSalvarImagemMouseClicked
javax.swing.JFileChooser fileChooser = new 
        javax.swing.JFileChooser(); 
fileChooser.setDialogTitle("Escolha uma imagem"); 

javax.swing.filechooser.FileNameExtensionFilter filter = new 
        javax.swing.filechooser.FileNameExtensionFilter( "Imagens JPG, PNG e GIF", "jpg", "jpeg", "png", "gif");
fileChooser.setFileFilter(filter); 

int userSelection = fileChooser.showOpenDialog(this); 
if (userSelection == javax.swing.JFileChooser.APPROVE_OPTION) { 
    try { 
        java.io.File selectedFile = fileChooser.getSelectedFile(); 
        String imagePath = selectedFile.getAbsolutePath(); 
        
        javax.swing.ImageIcon imageIcon = new 
        javax.swing.ImageIcon(imagePath);
        
        java.awt.Image image = imageIcon.getImage(); 
        java.awt.Image newimg = image.getScaledInstance(LbnImagem.getWidth(), LbnImagem.getHeight(), java.awt.Image.SCALE_SMOOTH); 
        javax.swing.ImageIcon finalIcon = new 
        javax.swing.ImageIcon(newimg);
        
        LbnImagem.setIcon(finalIcon); 
            
        LbnImagem.setText(""); 
    
    } catch (Exception e) { 
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar a imagem.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE); 
    } 
} 
    }//GEN-LAST:event_BtnSalvarImagemMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    int[] attackOrder;
    boolean[] playableCharacter;
    int currentCharacter;
    private void loadTeamInBattle(ArrayList<RpgCharacter> playerTeam, ArrayList<RpgCharacter> computerTeam){
        labelChar1Name.setText(playerTeam.get(0).getName());
        labelChar2Name.setText(playerTeam.get(1).getName());
        labelChar3Name.setText(playerTeam.get(2).getName());
        labelChar1HP.setText("HP: "+playerTeam.get(0).getStamina());
        labelChar2HP.setText("HP: "+playerTeam.get(1).getStamina());
        labelChar3HP.setText("HP: "+playerTeam.get(2).getStamina());
        //recebe os dados da tela TeamLoader
        //cria um array com a ordem de ação dos personagens
        //carrega os dados no frontend
        currentCharacter();
    }
    private void currentCharacter(){
        if(playableCharacter[currentCharacter]){
            loadPlayerAttack();
        }else{
            loadComputerAttack();
        }
        if(currentCharacter!=5){
            currentCharacter=0;
        }else{
            currentCharacter++;
        }
        currentCharacter();
        //lê o array com a ordem de ação dos personagens
        //se o personagem for do jogador
            //chama a função "loadPlayerAttack", passando o atual personagem como parâmetro
        //se for do computador
            //chama a função "loadComputerAttack", passando o atual personagem como parâmetro
        //modifica a variável que indica a posição do array
        //chama a função de novo
    }
    private void loadPlayerAttack(){
        //lê o personagem que vai agir
        //verifica a classe
        //se for guerreiro
            //atualiza o texto do botão "btnClassAttack" para "ataque de espada"
        //se for arqueiro
            //atualiza o texto do botão "btnClassAttack" para "ataque de flecha"
        //se for mago
            //atualiza o texto do botão "btnClassAttack" para "ataque mágico"
    }
    private void loadComputerAttack(){
        //lê o personagem que vai agir
        //seleciona aleatoriamente uma das funções "commonAttack", "specialAttack" ou "deflect"
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSalvarImagem;
    private javax.swing.JLabel LbnImagem;
    private javax.swing.JButton btnBattleRun;
    private javax.swing.JButton btnClassAttack;
    private javax.swing.JButton btnCommonAttack;
    private javax.swing.JButton btnDeflect;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbRpgClass;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelChar1HP;
    private javax.swing.JLabel labelChar1Name;
    private javax.swing.JLabel labelChar2HP;
    private javax.swing.JLabel labelChar2Name;
    private javax.swing.JLabel labelChar3HP;
    private javax.swing.JLabel labelChar3Name;
    private javax.swing.JLabel labelEnemy1HP;
    private javax.swing.JLabel labelEnemy1Name;
    private javax.swing.JLabel labelEnemy2HP;
    private javax.swing.JLabel labelEnemy2Name;
    private javax.swing.JLabel labelEnemy3HP;
    private javax.swing.JLabel labelEnemy3Name;
    private javax.swing.JLabel labelNameChar1;
    private javax.swing.JLabel labelNameChar2;
    private javax.swing.JLabel labelNameChar3;
    private javax.swing.JMenuItem miBattleCard;
    private javax.swing.JMenuItem miCharacterEditorCard;
    private javax.swing.JMenuItem miTeamEditorCard;
    private javax.swing.JTextField tfAgility;
    private javax.swing.JTextField tfCharacterName;
    private javax.swing.JTextField tfIntelligence;
    private javax.swing.JTextField tfStrength;
    private javax.swing.JTextField tfVitality;
    // End of variables declaration//GEN-END:variables
}
